services:
  mongo:
    image: mongo:7
    container_name: biblio-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biblio-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 5000
      JWT_SECRET: super_secret_jwt_key
      JWT_EXPIRES_IN: 1d
      MONGO_URI: mongodb://mongo:27017/biblio_db
    ports:
      - "5000:5000"
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biblio-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo_data:
  backend_uploads:
