require("dotenv").config();
const mongoose = require("mongoose");
const Book = require("./models/book.model");
const Category = require("./models/category.model");

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);

  const categories = await Category.find({
    name: { $in: ["Médecine", "Philosophie", "Roman policier", "Manga"] },
  });

  const cat = {};
  categories.forEach((c) => (cat[c.name] = c._id));

  const books = [
    /* ================= MEDECINE (5) ================= */
    {
      title: "Gray’s Anatomy",
      authors: ["Henry Gray"],
      isbn: "MED-001",
      description: "Classic anatomy reference.",
      coverImage: "https://archive.org/services/img/graysanatomy00grayuoft",
      fileUrl: "https://archive.org/download/graysanatomy00grayuoft/graysanatomy00grayuoft.pdf",
      fileType: "pdf",
      category: cat["Médecine"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1918-01-01"),
      totalCopies: 5,
      availableCopies: 5,
      tags: ["medicine", "anatomy"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Medical Microbiology",
      authors: ["UW Madison"],
      isbn: "MED-002",
      description: "Open access microbiology.",
      coverImage: "",
      fileUrl: "https://open.umn.edu/opentextbooks/textbooks/medical-microbiology.pdf",
      fileType: "pdf",
      category: cat["Médecine"],
      language: "English",
      publisher: "Open Textbook",
      publishedDate: new Date("2016-01-01"),
      totalCopies: 5,
      availableCopies: 5,
      tags: ["medicine", "biology"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Clinical Medicine",
      authors: ["Davidson"],
      isbn: "MED-003",
      description: "Clinical medicine overview.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Médecine"],
      language: "English",
      publisher: "Academic",
      publishedDate: new Date("2015-01-01"),
      totalCopies: 4,
      availableCopies: 4,
      tags: ["medicine", "clinical"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Human Physiology",
      authors: ["OpenStax"],
      isbn: "MED-004",
      description: "Open physiology textbook.",
      coverImage: "",
      fileUrl: "https://openstax.org/details/books/anatomy-and-physiology",
      fileType: "pdf",
      category: cat["Médecine"],
      language: "English",
      publisher: "OpenStax",
      publishedDate: new Date("2019-01-01"),
      totalCopies: 4,
      availableCopies: 4,
      tags: ["physiology"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Introduction to Nursing",
      authors: ["Open RN"],
      isbn: "MED-005",
      description: "Basics of nursing.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Médecine"],
      language: "English",
      publisher: "Open RN",
      publishedDate: new Date("2020-01-01"),
      totalCopies: 4,
      availableCopies: 4,
      tags: ["nursing"],
      ratings: { average: 0, count: 0 },
    },

    /* ================= PHILOSOPHIE (5) ================= */
    {
      title: "The Republic",
      authors: ["Plato"],
      isbn: "PHI-001",
      description: "Justice and society.",
      coverImage: "",
      fileUrl: "https://archive.org/download/republicofplato00platuoft/republicofplato00platuoft.pdf",
      fileType: "pdf",
      category: cat["Philosophie"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("-0380-01-01"),
      totalCopies: 6,
      availableCopies: 6,
      tags: ["philosophy"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Meditations",
      authors: ["Marcus Aurelius"],
      isbn: "PHI-002",
      description: "Stoic philosophy.",
      coverImage: "",
      fileUrl: "https://archive.org/download/meditations00marcuoft/meditations00marcuoft.pdf",
      fileType: "pdf",
      category: cat["Philosophie"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("0180-01-01"),
      totalCopies: 6,
      availableCopies: 6,
      tags: ["stoicism"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Thus Spoke Zarathustra",
      authors: ["Friedrich Nietzsche"],
      isbn: "PHI-003",
      description: "Philosophical novel.",
      coverImage: "",
      fileUrl: "https://archive.org/download/thusspokezarath00niet/thusspokezarath00niet.pdf",
      fileType: "pdf",
      category: cat["Philosophie"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1892-01-01"),
      totalCopies: 5,
      availableCopies: 5,
      tags: ["existentialism"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Beyond Good and Evil",
      authors: ["Nietzsche"],
      isbn: "PHI-004",
      description: "Morality critique.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Philosophie"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1886-01-01"),
      totalCopies: 5,
      availableCopies: 5,
      tags: ["ethics"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Critique of Pure Reason",
      authors: ["Immanuel Kant"],
      isbn: "PHI-005",
      description: "Modern philosophy.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Philosophie"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1781-01-01"),
      totalCopies: 5,
      availableCopies: 5,
      tags: ["reason"],
      ratings: { average: 0, count: 0 },
    },

    /* ================= ROMAN POLICIER (5) ================= */
    {
      title: "Sherlock Holmes Vol.1",
      authors: ["Arthur Conan Doyle"],
      isbn: "POL-001",
      description: "Detective stories.",
      coverImage: "",
      fileUrl: "https://archive.org/download/adventuresofsher00doyluoft/adventuresofsher00doyluoft.pdf",
      fileType: "pdf",
      category: cat["Roman policier"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1892-01-01"),
      totalCopies: 8,
      availableCopies: 8,
      tags: ["crime"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "The Hound of the Baskervilles",
      authors: ["Arthur Conan Doyle"],
      isbn: "POL-002",
      description: "Holmes mystery.",
      coverImage: "",
      fileUrl: "https://archive.org/download/houndofbaskervil00doyluoft/houndofbaskervil00doyluoft.pdf",
      fileType: "pdf",
      category: cat["Roman policier"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1902-01-01"),
      totalCopies: 8,
      availableCopies: 8,
      tags: ["mystery"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "The Secret Adversary",
      authors: ["Agatha Christie"],
      isbn: "POL-003",
      description: "Spy detective novel.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Roman policier"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1922-01-01"),
      totalCopies: 7,
      availableCopies: 7,
      tags: ["detective"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Murder on the Links",
      authors: ["Agatha Christie"],
      isbn: "POL-004",
      description: "Poirot mystery.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Roman policier"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1923-01-01"),
      totalCopies: 7,
      availableCopies: 7,
      tags: ["crime"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "The Big Four",
      authors: ["Agatha Christie"],
      isbn: "POL-005",
      description: "International crime.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Roman policier"],
      language: "English",
      publisher: "Public Domain",
      publishedDate: new Date("1927-01-01"),
      totalCopies: 7,
      availableCopies: 7,
      tags: ["mystery"],
      ratings: { average: 0, count: 0 },
    },

    /* ================= MANGA (5) ================= */
    {
      title: "Naruto Vol.1",
      authors: ["Masashi Kishimoto"],
      isbn: "MNG-001",
      description: "Young ninja story.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9781569319000-L.jpg",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Manga"],
      language: "Japanese",
      publisher: "Shueisha",
      publishedDate: new Date("1999-09-21"),
      totalCopies: 3,
      availableCopies: 3,
      tags: ["manga", "shonen"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "One Piece Vol.1",
      authors: ["Eiichiro Oda"],
      isbn: "MNG-002",
      description: "Pirate adventure.",
      coverImage: "https://covers.openlibrary.org/b/isbn/9781569319017-L.jpg",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Manga"],
      language: "Japanese",
      publisher: "Shueisha",
      publishedDate: new Date("1997-07-22"),
      totalCopies: 3,
      availableCopies: 3,
      tags: ["manga", "pirates"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Attack on Titan Vol.1",
      authors: ["Hajime Isayama"],
      isbn: "MNG-003",
      description: "Humanity vs Titans.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Manga"],
      language: "Japanese",
      publisher: "Kodansha",
      publishedDate: new Date("2009-09-09"),
      totalCopies: 3,
      availableCopies: 3,
      tags: ["manga", "action"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Dragon Ball Vol.1",
      authors: ["Akira Toriyama"],
      isbn: "MNG-004",
      description: "Martial arts adventure.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Manga"],
      language: "Japanese",
      publisher: "Shueisha",
      publishedDate: new Date("1984-11-20"),
      totalCopies: 3,
      availableCopies: 3,
      tags: ["manga"],
      ratings: { average: 0, count: 0 },
    },
    {
      title: "Death Note Vol.1",
      authors: ["Tsugumi Ohba"],
      isbn: "MNG-005",
      description: "Psychological thriller.",
      coverImage: "",
      fileUrl: "",
      fileType: "pdf",
      category: cat["Manga"],
      language: "Japanese",
      publisher: "Shueisha",
      publishedDate: new Date("2003-12-01"),
      totalCopies: 3,
      availableCopies: 3,
      tags: ["manga", "thriller"],
      ratings: { average: 0, count: 0 },
    },
  ];

  await Book.insertMany(books);
  console.log("✅ 20 livres insérés avec succès");
  process.exit();
}

seed();
